name: api_console_client
description: Client console Dart pour l'API REST

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.5
  args: ^2.3.1        # Pour le parsing des arguments CLI
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0